"""initial schema

Revision ID: 16dd05bf91df
Revises:
Create Date: 2026-07-18 17:52:33.145112

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "16dd05bf91df"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added: autogenerate does not know about extensions, and every
    # citext column below fails without it.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("lastfm_name", sa.Text(), nullable=False),
        sa.Column("lastfm_mbid", sa.String(length=36), nullable=True),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("listed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delisted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("slope_microcents_per_share", sa.BigInteger(), nullable=True),
        sa.Column("anchor_cents", sa.BigInteger(), nullable=True),
        sa.Column("anchor_target_cents", sa.BigInteger(), nullable=True),
        sa.Column("glide_start_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("glide_end_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("tier IN ('growth', 'blue_chip')", name=op.f("ck_artists_tier_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artists")),
        sa.UniqueConstraint("slug", name=op.f("uq_artists_slug")),
    )
    op.create_table(
        "magic_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_magic_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_magic_links_token_hash")),
    )
    op.create_index(op.f("ix_magic_links_email"), "magic_links", ["email"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "balance_cache",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("cash_cents", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_balance_cache_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_balance_cache")),
    )
    op.create_table(
        "flagged_artists",
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("cleared_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("cleared_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_flagged_artists_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artist_id", "as_of_date", name=op.f("pk_flagged_artists")),
    )
    op.create_table(
        "index_snapshots",
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("index_score", sa.Float(), nullable=False),
        sa.Column("fair_value_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "components",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_index_snapshots_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artist_id", "as_of_date", name=op.f("pk_index_snapshots")),
    )
    op.create_index(
        "ix_index_snapshots_as_of_date", "index_snapshots", ["as_of_date"], unique=False
    )
    op.create_table(
        "metric_snapshots",
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_metric_snapshots_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "artist_id", "as_of_date", "source", "metric_key", name=op.f("pk_metric_snapshots")
        ),
    )
    op.create_table(
        "position_cache",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("shares", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "avg_cost_microcents", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "realized_pnl_cents", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("scout_shares", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_position_cache_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_position_cache_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_id", name=op.f("pk_position_cache")),
    )
    op.create_table(
        "price_history",
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("market_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("fair_value_cents", sa.BigInteger(), nullable=True),
        sa.Column("net_supply", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "source IN ('trade', 'reversion', 'listing')",
            name=op.f("ck_price_history_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_price_history_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artist_id", "at", name=op.f("pk_price_history")),
    )
    op.create_index(
        "ix_price_history_artist_id_at", "price_history", ["artist_id", "at"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("artist_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("cash_delta_cents", sa.BigInteger(), nullable=False),
        sa.Column("share_delta", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("exec_price_cents", sa.BigInteger(), nullable=True),
        sa.Column("index_score_at_trade", sa.Float(), nullable=True),
        sa.Column("fair_value_cents_at_trade", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('GRANT', 'BUY', 'SELL', 'FEE')", name=op.f("ck_transactions_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_transactions_artist_id_artists"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_transactions_idempotency_key")),
    )
    op.create_index(
        "ix_transactions_artist_id_created_at",
        "transactions",
        ["artist_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_id_created_at",
        "transactions",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_id_created_at", table_name="transactions")
    op.drop_index("ix_transactions_artist_id_created_at", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_price_history_artist_id_at", table_name="price_history")
    op.drop_table("price_history")
    op.drop_table("position_cache")
    op.drop_table("metric_snapshots")
    op.drop_index("ix_index_snapshots_as_of_date", table_name="index_snapshots")
    op.drop_table("index_snapshots")
    op.drop_table("flagged_artists")
    op.drop_table("balance_cache")
    op.drop_table("users")
    op.drop_index(op.f("ix_magic_links_email"), table_name="magic_links")
    op.drop_table("magic_links")
    op.drop_table("artists")
    # ### end Alembic commands ###

    # citext is deliberately NOT dropped. On a shared database another
    # schema may depend on it, and leaving it costs nothing — `CREATE
    # EXTENSION IF NOT EXISTS` on the way back up is a no-op.
