"""add leaderboard sort indexes

Revision ID: 8900c4e149ac
Revises: e3a622ae9505
Create Date: 2026-07-21 20:21:41.064490

"""

from collections.abc import Sequence

from alembic import op

revision: str = "8900c4e149ac"
down_revision: str | None = "e3a622ae9505"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_equity_snapshots_as_of_date_equity_cents",
        "equity_snapshots",
        ["as_of_date", "equity_cents"],
        unique=False,
    )
    op.create_index(
        "ix_leaderboard_scout_as_of_date_return_bps",
        "leaderboard_scout",
        ["as_of_date", "return_bps"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_leaderboard_scout_as_of_date_return_bps", table_name="leaderboard_scout")
    op.drop_index("ix_equity_snapshots_as_of_date_equity_cents", table_name="equity_snapshots")
    # ### end Alembic commands ###
