"""phase6 leaderboards

Revision ID: e3a622ae9505
Revises: 61956f34881f
Create Date: 2026-07-21 17:36:10.784906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e3a622ae9505"
down_revision: str | None = "61956f34881f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equity_snapshots",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("equity_cents", sa.BigInteger(), nullable=False),
        sa.Column("cash_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_equity_snapshots_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "as_of_date", name=op.f("pk_equity_snapshots")),
    )
    op.create_index(
        "ix_equity_snapshots_as_of_date", "equity_snapshots", ["as_of_date"], unique=False
    )
    op.create_table(
        "leaderboard_scout",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("best_artist_id", sa.BigInteger(), nullable=False),
        sa.Column("entry_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("return_bps", sa.BigInteger(), nullable=False),
        sa.Column("scout_shares", sa.BigInteger(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["best_artist_id"],
            ["artists.id"],
            name=op.f("fk_leaderboard_scout_best_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_leaderboard_scout_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_leaderboard_scout")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leaderboard_scout")
    op.drop_index("ix_equity_snapshots_as_of_date", table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    # ### end Alembic commands ###
