/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Signup
         * @description Request step of verify-before-create signup. Always 202 regardless
         *     of which branch below fires -- same anti-enumeration shape
         *     `/auth/magic-link` already uses, so a prober can't distinguish "this
         *     address already has an account" from "a new signup was queued".
         */
        post: operations["request_signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume Signup
         * @description Creates `users` + the `GRANT` ledger row + a `Session`, all in one
         *     transaction (the same shape Phase 4's one-shot signup used, just
         *     moved behind email verification).
         *
         *     Username collision handling has one rule: a value nobody chose (this
         *     request omitted `username` *and* the original request did too) is
         *     the server's problem, retried in-process with a fresh generated
         *     candidate; a value somebody chose -- typed at request time, or
         *     supplied again here -- is a 409 for the caller to resolve, and
         *     `consumed_at` is deliberately left unset so the token (proof of inbox
         *     ownership) is still good for a retry against a different username.
         */
        post: operations["consume_signup_auth_signup_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Username */
        patch: operations["update_username_auth_username_patch"];
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Idempotent and cookie-first: clears the cookie even if the session
         *     it names is already gone, expired, or was never valid -- a client
         *     retrying a logout that "failed" on the network must not get stuck
         *     unable to clear its own browser state.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Magic Link
         * @description Recovery on a new device: request a login link for an existing
         *     account. Always returns the same response whether or not the email
         *     is registered -- a differing response would let anyone probe which
         *     addresses have accounts.
         */
        post: operations["request_magic_link_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume Magic Link */
        post: operations["consume_magic_link_auth_magic_link_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote Trade
         * @description Read-only preview -- no lock, no writes. A trade quoted here can
         *     still fail at execution time if state moved in between; that's
         *     inherent to previewing a live market, not a bug.
         */
        post: operations["quote_trade_trades_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Trade */
        post: operations["execute_trade_trades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artists */
        get: operations["list_artists_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist */
        get: operations["get_artist_artists__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{slug}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist History */
        get: operations["get_artist_history_artists__slug__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio History
         * @description Real daily equity, oldest first -- written by `jobs/leaderboard.py`,
         *     not computed live. A brand-new account, or one that signed up before
         *     tonight's job has run once, legitimately has zero points: the
         *     frontend's `PortfolioValueChart` already renders an honest "not
         *     enough history yet" state for fewer than two points, so there is
         *     nothing to backfill or fake here (CLAUDE.md: an honest absence beats
         *     a stub).
         */
        get: operations["get_portfolio_history_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/flagged-artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flagged Artists */
        get: operations["list_flagged_artists_admin_flagged_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/flagged-artists/{artist_id}/{as_of_date}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Flagged Artist */
        post: operations["clear_flagged_artist_admin_flagged_artists__artist_id___as_of_date__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Leaderboard */
        get: operations["get_portfolio_leaderboard_leaderboard_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/scout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scout Leaderboard */
        get: operations["get_scout_leaderboard_leaderboard_scout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only — deliberately does not touch the database.
         *
         *     Railway restarts a container that fails its health check. If this
         *     probed Postgres, a brief DB blip would kill an otherwise healthy API
         *     and turn a recoverable incident into a restart loop.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistOut */
        ArtistOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /**
             * Listed At
             * Format: date-time
             */
            listed_at: string;
            /** Spot Price Cents */
            spot_price_cents: number;
            /** Net Supply */
            net_supply: number;
            /** Index Score */
            index_score: number | null;
            /** Fair Value Cents */
            fair_value_cents: number | null;
            /** Daily Change Pct */
            daily_change_pct: number | null;
        };
        /** ConsumeResponse */
        ConsumeResponse: {
            user: components["schemas"]["UserOut"];
        };
        /** DetailResponse */
        DetailResponse: {
            /** Detail */
            detail: string;
        };
        /** EmailRequest */
        EmailRequest: {
            /** Email */
            email: string;
        };
        /** EquityPoint */
        EquityPoint: {
            /** As Of Date */
            as_of_date: string;
            /** Equity Cents */
            equity_cents: number;
            /** Cash Cents */
            cash_cents: number;
        };
        /** FlaggedArtistOut */
        FlaggedArtistOut: {
            /** Artist Id */
            artist_id: number;
            /** Artist Slug */
            artist_slug: string;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Reason */
            reason: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Cleared At */
            cleared_at: string | null;
            /** Cleared By */
            cleared_by: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Market Price Cents */
            market_price_cents: number;
            /** Fair Value Cents */
            fair_value_cents: number | null;
            /** Net Supply */
            net_supply: number;
            /** Source */
            source: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            artist: components["schemas"]["ArtistOut"];
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
        };
        /** MagicLinkConsumeRequest */
        MagicLinkConsumeRequest: {
            /** Token */
            token: string;
        };
        /** PortfolioHistoryResponse */
        PortfolioHistoryResponse: {
            /** Points */
            points: components["schemas"]["EquityPoint"][];
        };
        /** PortfolioLeaderboardResponse */
        PortfolioLeaderboardResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Rows */
            rows: components["schemas"]["PortfolioLeaderboardRow"][];
            you: components["schemas"]["PortfolioLeaderboardRow"] | null;
        };
        /** PortfolioLeaderboardRow */
        PortfolioLeaderboardRow: {
            /** Rank */
            rank: number;
            /** Username */
            username: string;
            /** Return Bps */
            return_bps: number;
            /** Is You */
            is_you: boolean;
        };
        /** PortfolioPosition */
        PortfolioPosition: {
            /** Artist Slug */
            artist_slug: string;
            /** Artist Name */
            artist_name: string;
            /** Shares */
            shares: number;
            /** Avg Cost Cents */
            avg_cost_cents: number;
            /** Spot Price Cents */
            spot_price_cents: number;
            /** Market Value Cents */
            market_value_cents: number;
            /** Unrealized Pnl Cents */
            unrealized_pnl_cents: number;
            /** Realized Pnl Cents */
            realized_pnl_cents: number;
            /** Scout Shares */
            scout_shares: number;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Cash Cents */
            cash_cents: number;
            /** Equity Cents */
            equity_cents: number;
            /** Positions */
            positions: components["schemas"]["PortfolioPosition"][];
        };
        /** QuoteResponse */
        QuoteResponse: {
            side: components["schemas"]["TradeSide"];
            /** Shares */
            shares: number;
            /** Amount Cents */
            amount_cents: number;
            /** Fee Cents */
            fee_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Exec Price Cents */
            exec_price_cents: number;
            /** Spot Before Cents */
            spot_before_cents: number;
            /** Spot After Cents */
            spot_after_cents: number;
            /** Violations */
            violations: string[];
        };
        /** ScoutLeaderboardResponse */
        ScoutLeaderboardResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Rows */
            rows: components["schemas"]["ScoutLeaderboardRow"][];
            you: components["schemas"]["ScoutLeaderboardRow"] | null;
        };
        /** ScoutLeaderboardRow */
        ScoutLeaderboardRow: {
            /** Rank */
            rank: number;
            /** Username */
            username: string;
            /** Artist Slug */
            artist_slug: string;
            /** Artist Name */
            artist_name: string;
            /** Entry Price Cents */
            entry_price_cents: number;
            /** Return Bps */
            return_bps: number;
            /** Is You */
            is_you: boolean;
        };
        /** SignupConsumeRequest */
        SignupConsumeRequest: {
            /** Token */
            token: string;
            /** Username */
            username?: string | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Username */
            username?: string | null;
        };
        /** SignupResponse */
        SignupResponse: {
            user: components["schemas"]["UserOut"];
            /** Cash Cents */
            cash_cents: number;
        };
        /** TradeRequest */
        TradeRequest: {
            /** Artist Slug */
            artist_slug: string;
            side: components["schemas"]["TradeSide"];
            /** Shares */
            shares: number;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** TradeResponse */
        TradeResponse: {
            /** Transaction Id */
            transaction_id: number;
            side: components["schemas"]["TradeSide"];
            /** Shares */
            shares: number;
            /** Exec Price Cents */
            exec_price_cents: number;
            /** Fee Cents */
            fee_cents: number;
            /** Cash Cents */
            cash_cents: number;
            /** Position Shares */
            position_shares: number;
            /** Idempotent Replay */
            idempotent_replay: boolean;
        };
        /**
         * TradeSide
         * @enum {string}
         */
        TradeSide: "buy" | "sell";
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
        };
        /** UsernameUpdateRequest */
        UsernameUpdateRequest: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consume_signup_auth_signup_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupConsumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_username_auth_username_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsernameUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_magic_link_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consume_magic_link_auth_magic_link_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkConsumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_trade_trades_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_trade_trades_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artists_artists_get: {
        parameters: {
            query?: {
                tier?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artist_artists__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artist_history_artists__slug__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_history_portfolio_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flagged_artists_admin_flagged_artists_get: {
        parameters: {
            query?: {
                include_cleared?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlaggedArtistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_flagged_artist_admin_flagged_artists__artist_id___as_of_date__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: number;
                as_of_date: string;
            };
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_leaderboard_leaderboard_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scout_leaderboard_leaderboard_scout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ax_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoutLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
